"""Added new column

Revision ID: 1df477c43e44
Revises: 
Create Date: 2024-12-20 15:17:50.958948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df477c43e44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_Email', table_name='User')
    op.drop_index('ix_User_Nome', table_name='User')
    op.drop_index('ix_User_Senha', table_name='User')
    op.drop_index('ix_User_UserId', table_name='User')
    op.drop_table('User')
    op.drop_index('IFK_CustomerSupportRepId', table_name='Customer')
    op.drop_table('Customer')
    op.drop_index('IFK_InvoiceCustomerId', table_name='Invoice')
    op.drop_table('Invoice')
    op.drop_table('Genre')
    op.drop_table('Artist')
    op.drop_index('IFK_InvoiceLineInvoiceId', table_name='InvoiceLine')
    op.drop_index('IFK_InvoiceLineTrackId', table_name='InvoiceLine')
    op.drop_table('InvoiceLine')
    op.drop_table('Playlist')
    op.drop_index('IFK_TrackAlbumId', table_name='Track')
    op.drop_index('IFK_TrackGenreId', table_name='Track')
    op.drop_index('IFK_TrackMediaTypeId', table_name='Track')
    op.drop_table('Track')
    op.drop_index('IFK_AlbumArtistId', table_name='Album')
    op.drop_table('Album')
    op.drop_index('IFK_EmployeeReportsTo', table_name='Employee')
    op.drop_table('Employee')
    op.drop_table('MediaType')
    op.drop_table('Customers')
    op.drop_index('IFK_PlaylistTrackTrackId', table_name='PlaylistTrack')
    op.drop_table('PlaylistTrack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlaylistTrack',
    sa.Column('PlaylistId', sa.INTEGER(), nullable=False),
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['PlaylistId'], ['Playlist.PlaylistId'], ),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], ),
    sa.PrimaryKeyConstraint('PlaylistId', 'TrackId')
    )
    op.create_index('IFK_PlaylistTrackTrackId', 'PlaylistTrack', ['TrackId'], unique=False)
    op.create_table('Customers',
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('FirstName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('LastName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Company', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('City', sa.VARCHAR(length=100), nullable=True),
    sa.Column('State', sa.VARCHAR(length=50), nullable=True),
    sa.Column('Country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('PostalCode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('Fax', sa.VARCHAR(length=50), nullable=True),
    sa.Column('Email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('SupportRepId', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerId'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('MediaType',
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('MediaTypeId')
    )
    op.create_table('Employee',
    sa.Column('EmployeeId', sa.INTEGER(), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ReportsTo', sa.INTEGER(), nullable=True),
    sa.Column('BirthDate', sa.DATETIME(), nullable=True),
    sa.Column('HireDate', sa.DATETIME(), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['ReportsTo'], ['Employee.EmployeeId'], ),
    sa.PrimaryKeyConstraint('EmployeeId')
    )
    op.create_index('IFK_EmployeeReportsTo', 'Employee', ['ReportsTo'], unique=False)
    op.create_table('Album',
    sa.Column('AlbumId', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=160), nullable=False),
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ArtistId'], ['Artist.ArtistId'], ),
    sa.PrimaryKeyConstraint('AlbumId')
    )
    op.create_index('IFK_AlbumArtistId', 'Album', ['ArtistId'], unique=False)
    op.create_table('Track',
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('AlbumId', sa.INTEGER(), nullable=True),
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('GenreId', sa.INTEGER(), nullable=True),
    sa.Column('Composer', sa.NVARCHAR(length=220), nullable=True),
    sa.Column('Milliseconds', sa.INTEGER(), nullable=False),
    sa.Column('Bytes', sa.INTEGER(), nullable=True),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['AlbumId'], ['Album.AlbumId'], ),
    sa.ForeignKeyConstraint(['GenreId'], ['Genre.GenreId'], ),
    sa.ForeignKeyConstraint(['MediaTypeId'], ['MediaType.MediaTypeId'], ),
    sa.PrimaryKeyConstraint('TrackId')
    )
    op.create_index('IFK_TrackMediaTypeId', 'Track', ['MediaTypeId'], unique=False)
    op.create_index('IFK_TrackGenreId', 'Track', ['GenreId'], unique=False)
    op.create_index('IFK_TrackAlbumId', 'Track', ['AlbumId'], unique=False)
    op.create_table('Playlist',
    sa.Column('PlaylistId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('PlaylistId')
    )
    op.create_table('InvoiceLine',
    sa.Column('InvoiceLineId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('Quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['InvoiceId'], ['Invoice.InvoiceId'], ),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], ),
    sa.PrimaryKeyConstraint('InvoiceLineId')
    )
    op.create_index('IFK_InvoiceLineTrackId', 'InvoiceLine', ['TrackId'], unique=False)
    op.create_index('IFK_InvoiceLineInvoiceId', 'InvoiceLine', ['InvoiceId'], unique=False)
    op.create_table('Artist',
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('ArtistId')
    )
    op.create_table('Genre',
    sa.Column('GenreId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('GenreId')
    )
    op.create_table('Invoice',
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceDate', sa.DATETIME(), nullable=False),
    sa.Column('BillingAddress', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('BillingCity', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingState', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingCountry', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingPostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customer.CustomerId'], ),
    sa.PrimaryKeyConstraint('InvoiceId')
    )
    op.create_index('IFK_InvoiceCustomerId', 'Invoice', ['CustomerId'], unique=False)
    op.create_table('Customer',
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Company', sa.NVARCHAR(length=80), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=False),
    sa.Column('SupportRepId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['SupportRepId'], ['Employee.EmployeeId'], ),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    op.create_index('IFK_CustomerSupportRepId', 'Customer', ['SupportRepId'], unique=False)
    op.create_table('User',
    sa.Column('UserId', sa.INTEGER(), nullable=False),
    sa.Column('Nome', sa.VARCHAR(), nullable=True),
    sa.Column('Email', sa.VARCHAR(), nullable=True),
    sa.Column('Senha', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index('ix_User_UserId', 'User', ['UserId'], unique=False)
    op.create_index('ix_User_Senha', 'User', ['Senha'], unique=False)
    op.create_index('ix_User_Nome', 'User', ['Nome'], unique=False)
    op.create_index('ix_User_Email', 'User', ['Email'], unique=False)
    # ### end Alembic commands ###
